### ISSUE TITLE
[Bug] Distance check update breaks existing alerts with null 0

### ISSUE THREAD

**Issue by Megaddd** [adamk33n3r/runelite-watchdog#150]
**Describe the bug**
After the update adding the distance check, existing alerts will display a null comparator with 0 distance, rendering any existing alerts non-functional.

**Expected behavior**
pre-existing Alerts should work as expected without a distance check factor (i.e. >0)

**Comment by adamk33n3r** [comment]
This is disappointing because I thought I set defaults but apparently the way I did it didn't work :'( Unfortunately there's nothing I can do for existing users, as it would require a new release which would take multiple weeks.

But in the meantime, fixing the `null` comparator and setting the distance to `-1` should get it working again.

**Comment by adamk33n3r** [comment]
Going to re-open this to track the issue to fix the defaults
