### ISSUE TITLE
[Bug] Karuulm Slayer Dungeon Drake area is a banned area

### ISSUE THREAD

**Issue by CreativeTechGuy** [adamk33n3r/runelite-watchdog#156]
**Describe the bug**

Watchdog is disabled in the north-east corner of the Drake task-only area.

**To Reproduce**
Go to the Drakes on the middle level of the dungeon here:
![image](https://github.com/adamk33n3r/runelite-watchdog/assets/12002072/c5c2b0ea-07bf-4e2d-9362-27a7a0a4b9fd)

See Watchdog with a red name/icon and alerts do not fire.

**Expected behavior**

Alerts would work in all areas of the dungeon except inside of the Alchemical Hydra boss arena.

**Comment by adamk33n3r** [comment]
I think we talked about this in the discord, but the reason this happens is because that corner is in the same region block as the boss below, and we are solely checking against region id.

A potential solution here would be to further restrict to region id + floor number. The issue I have with that is that makes it so that you have to add floor numbers to every other blocked region (or perhaps default to "any"), and it just adds complexity. I'm not opposed to finding a solution, but right now it seems like it would be adding a lot of complexity.

If you, or someone, would like to make a PR implementing a solution that checks for floors for this region, but does any for others (important for raids), I would take a look.
