### ISSUE TITLE
[Feature] Add delay to alerts

### ISSUE THREAD

**Issue by pettrs** [adamk33n3r/runelite-watchdog#17]
Please increase the debounce time limit from 60 seconds to 120 seconds! 

I'm doing GOTR and using an AFK method where I need a notification to ping me 10 seconds prior to the first altar opening. due to the only consistent chat message being 120 seconds prior to its opening, there is no way to set a notification 10 seconds prior to it opening. chat notification doesn't support delaying notifications, even with the runelite delay. my intent is to set the notification to ping on the game starting and delay that by 110 seconds so that I know 10 seconds before it opens.

I hope there aren't any downsides to this, thank you very much.

**Comment by pettrs** [comment]
I'm sorry, I think I might have misunderstood what the debounce timer did. Can there be an additional function that delays the time from when the notification is triggered to when it pings? I might want to be notified 10 seconds after a chat notification appears. and if so, can this delay function be up to at least 120 seconds?

**Comment by adamk33n3r** [comment]
Ya the debounce is for when the alert would fire a lot in quick succession. Like for example if all of your crops were ready to harvest at once, this lets you not have it fire 6 times at once.

Adding a delay is an interesting suggestion. I can see the use case here, but I think it would be limited to things like this. I'll think about adding this, I just don't want to be cluttering up the UI especially after I just updated it to be cleaner :P it will be low priority for now.

If others 👍🏻 this issue I'll make it higher priority.

**Comment by adamk33n3r** [comment]
One question I have is should this be at the alert level or at the notification level?

**Comment by pettrs** [comment]
Can you elaborate on what you mean by this?

**Comment by adamk33n3r** [comment]
Like, would the "delay" be put at the alert level so that all notifications are fired after that delay? Or would the "delay" be put at every notification level so that each notification for an alert can have a separate delay.

I would argue that it should be at the alert level because it's not as messy and it's probably not really that useful to have it be different per notification.

**Comment by pettrs** [comment]
the delay would be for each individual plugin, not for all simultaneously. 

Game message -> triggers alert -> x seconds delay -> triggers notification

**Comment by adamk33n3r** [comment]
IDK if this would be helpful for you, but there is a new plugin under review for AFK GOTR https://github.com/runelite/plugin-hub/pull/3788

**Comment by pettrs** [comment]
ye but it doesn't do what I want it to do.

**Comment by Cisney-Gassai** [comment]
It has been a year, and this still hasn't been implemented. This would be really helpful.

Here's my use case:

When I throw a fishing explosive into the kraken whirlpool, it triggers a game message. However, I want to hear a sound notification only a few seconds afterward because it cannot be attacked right away.

Similarly, when it dies, I receive the KC message for the alert, but I cannot throw another fishing explosive until a few seconds later. Therefore, I could use another sound to know when I can throw it again.

I'm sure I have encountered more situations where a delay would be helpful.

**Comment by PcoteStudio** [comment]
Another use case is to get notified just before GWD bosses spawn based on their death game message. This feature would be really helpful for many use cases.
