### ISSUE TITLE
Trigger sound ID alerts without sound being turned on

### ISSUE THREAD

**Issue by Gollum69** [adamk33n3r/runelite-watchdog#21]
Fantastic way to produce notifications with a sound ID, however I would still like the notifications to be produced whilst the audio settings are muted. I could just keep the sound effects at 1% so they continue working but I like to complain

**Comment by adamk33n3r** [comment]
Oh is that how it works? If it's muted in the game it doesn't fire a notification? If that's the case then I actually don't think there is anything I can do about it unfortunately. I'm just listening to the "SoundEffectPlayed" event so if the volume is muted then it must not fire that event. I will ask about it to the devs to verify.

**Comment by Gollum69** [comment]
When I click the 'test notification' button, it does fire the notification with all sounds muted, but when I go to the actual NPC for the sound ID to fire it, it does not fire it with sounds muted. I then put sound effects on and it works. I'll attach a clip [here](https://streamable.com/yvsgpl)

**Comment by adamk33n3r** [comment]
The Test button just fires the notification, it doesn't emulate the trigger. So that makes sense. I asked the runelite devs and it seems they just straight up don't fire/play the sound if it's muted so unfortunately, I don't think we can do anything about it. If it's not played, we can't detect it was played. Sorry!

**Comment by Gollum69** [comment]
It’s ok I will enjoy my 1% of sound effects
