### ISSUE TITLE
[Feature] Support RL Tray Notifications

### ISSUE THREAD

**Issue by Newbcake** [adamk33n3r/runelite-watchdog#26]
Currently the plugin doesn't support sending notifications through the RL Tray notifications plugin: https://github.com/Trevor159/runelite-external-plugins/tree/tray-notifications

Could this possibly be supported?

**Comment by adamk33n3r** [comment]
External plugins aren't really able to communicate with each other, sorry.

**Comment by Newbcake** [comment]
I probably wasn't clear in explaining my issue fully, allow me to explain:

Most if not all of the (plugin hub) plugins that send notifications do so even with the RL tray notifications plugin, an easy one to test for example is thrall reminder. But I can't get any of the watchdog notifications to show up at all, they work fine with windows native notifications but not the RL tray notifications replacement.

You mentioned external plugins can't really communicate with eachother and I get that, however other plugins seems to send notifications just fine with this replacement plugin? So I was wondering if watchdog could be adapted to do the same. 

Most other plugins seem to use `notifier.notify()` to fire notifications, you seem to be using a custom implementation? Apologies if I am incorrect, my java knowledge is nonexistent. 

Hope my request is clearer now 😅 If still now possible then I'd be curious as to why if you would happen to know

**Comment by adamk33n3r** [comment]
Oh ok I get you know. So, the way that other plugins "hook into" the the RL Tray notifications plugin is because they are just firing notification fired events on the bus. The tray notifications plugin is just listening for those events. That's really all there is.

Now technically Watchdog could fire its own events. But the whole point of Watchdog is to be the consumer of them, not the producer. I suppose I could add a "Notification" type that all it does is put an event on the bus. How does that sound?

**Comment by Newbcake** [comment]
I'm not quite sure what you mean by Watching being the consumer of them. I mean I understand that watchdog can trigger on notifications. But it can also produce its own tray notifications as a result of a trigger, right?

Either way, my request specficially is that if I setup a watchdog workflow like this:
![RuneLite_2023-02-04_18-25-50](https://user-images.githubusercontent.com/9064744/216781075-08ebd031-4234-4036-9aed-e584268937e3.png)

Which in turn produces a notification:
![NVIDIA_Share_2023-02-04_18-26-33](https://user-images.githubusercontent.com/9064744/216781083-f1911ac8-fcbd-4663-a3d7-4b8f78cfc8d1.png)

I simply want that notification to show when I use the RL Tray notifications plugin to replace the native windows notifications.

If your proposal allows that to work properly, then yes that sounds good.

**Comment by adamk33n3r** [comment]
>I'm not quite sure what you mean by Watching being the consumer of them

I mean that it's meant to do things based on notifications, not create them itself. And by notifications i mean the `NotificationFired` RuneLite event.

>But it can also produce its own tray notifications as a result of a trigger, right?

Watchdog is producing the tray notification manually. It's not using the code that RuneLite uses to produce them, that's why RL Tray Notifications doesn't "work". Cause it's not doing the thing that RL Tray is listening for. Normally plugins will call `notifier.notify("Sote death ball is on you")` for example. This will then create a `NotificationFired` event and put it on the bus. It will then perform the notification types built into RuneLite like screenflash, sound, game message, etc. But if you're using Watchdog you probably have those off. Anyway, creating that event triggers all listeners for that event which includes RL Tray. RL Tray then creates its own custom tray notification based on the message in the event.

Hopefully that explains why RL Tray doesn't "work" with Watchdog. Watchdog isn't using the mechanism that RL Tray uses. My proposal will let that happen. I just have to make sure that I don't process the notification myself (with the `NotificationFired` trigger type) otherwise we could get in an infinite loop lol.
