### ISSUE TITLE
Possible to create a version without the TTS part? 

### ISSUE THREAD

**Issue by mparsakia** [adamk33n3r/runelite-watchdog#3]
Hey! I'd like to use this plugin but I have no intention of using the TTS part and would not like my IP being sent to a 3rd party server. Is it possible to create a fork / another plugin on the plugin hub that doesn't involve the 3rd party server warning?

**Comment by adamk33n3r** [comment]
In general I don't think creating forks of plugins to be hosted on the hub would be a good precedent. But I think there's a couple things we could do here. First of all, the plugin will only make a request to the server if you ask it to play TTS. So if you never do that (either by clicking test or by an alert firing) then the server is never hit. I know that's fragile, but in the meantime it's something.

As a long term solution, I could introduce a global tts-disable setting. Could maybe even default it on so that you have to opt-in specifically for the tts.

**Comment by mparsakia** [comment]
Thanks for the input! I just blocked the domain in my hosts file, however, if the domain was ever changed in the plugin, or worse hacked / registry lapsed and stolen it could be an issue. The IP warning on RL definitely is keeping the installs down, and it's such a good plugin to have certain things force notifications, i.e I use it for Prayer and HP while focused, with the rest like skilling only out of focus.

Unfortunately I'm not a Java/Kotlin developer but if I can help contribute in any way please let me know. I only have one possible idea for the TTS that would be using some code/library that allows the RL plugin to do TTS locally on device, without sending a string of text to a website.

**Comment by adamk33n3r** [comment]
I, and many others, have tried to use local TTS libraries in plugins but they've all been denied because of security concerns (also file size is pretty large) so this was the only way for us to get any form of TTS in.

I wouldn't have thought the RL warning would deter that many people, but maybe that sort of thing scares more people than I would expect. Even though anytime anyone visits any website they get their ip....haha. There might be precedent for removing the warning as long as the tts is opt-in.

**Comment by adamk33n3r** [comment]
Pending plugin hub release

**Comment by adamk33n3r** [comment]
This is now released on the plugin hub! 🎉
