### ISSUE TITLE
[Feature Request] Alert Type: Special Attack%

### ISSUE THREAD

**Issue by Popedigoz** [adamk33n3r/runelite-watchdog#42]
I would love to set an alert for when I get 100% special attack.

**Comment by Newbcake** [comment]
Adittional request: make the percentage configurable instead of a flat 100%

**Comment by adamk33n3r** [comment]
Funnily enough, I actually had a "resource" alert in early development that was going to track special attack, run energy, and hp, but I never ended up implementing it because I introduced the `Notification Fired` alert type. You should be able to use the notification from `Idle Notifier` to create a custom alert for special attack. Let me know if you need help with that or if it doesn't fit your needs!

**Comment by Popedigoz** [comment]
It's working, thank you.

**Comment by adamk33n3r** [comment]
Awesome!
