### ISSUE TITLE
Feature Request: Delay between Notifications

### ISSUE THREAD

**Issue by Marstead** [adamk33n3r/runelite-watchdog#5]
Thanks again for this amazing plugin, being able to set individual notification behavior is something I've wanted in RuneLite for years. I actually scrolled right past this one several times not understanding from the Plugin Hub description that this was providing that functionality!

Right now, certain types of useful context-sensitive alerts my fight rapidly in succession if the same message appears repeatedly. For instance, if you set an Alert for "You need to empty your coin pouches" while spam clicking a guard, you'll hear a lot of alerts fire back-to-back. It might be nice to be able to set a global minimum delay between duplicate alerts being fired. I'd envision a "Minimum Delay for Repeat Alerts" field where I could set how many seconds I'd like to suppress further alerts from the same source until they are allowed to fire again for that source.

Thank you again for the great plugin!

**Comment by adamk33n3r** [comment]
> I actually scrolled right past this one several times not understanding from the Plugin Hub description that this was providing that functionality!

Do you have an idea for a better description? I'd love to make it better. 

You seem to be describing a debounce functionality. I very much like this idea because ya, I know that sometimes you can get spammed haha. There are two different avenues I can envision. One being easier to implement than the other.

The first is just a global debounce. Only alert (at all) if there hasn't been anything triggered in the past x milliseconds. This would be fairly easy to implement but I see its downfalls. It could potentially be an interem solution to the next solution. 

The second is to have the debounce per source (or Alert). This is the more desirable solution but it would take a lot more work to design and implement. It doesn't seem too bad though. I could just create a lookup table with each Alert and the timestamp of the last trigger.

**Comment by Marstead** [comment]
![image](https://user-images.githubusercontent.com/54672873/199751196-b93ae7ba-aa37-4f5c-8521-600666895208.png)
This is the description I get on the browser plugin hub and in-game plugin hub for Watchdog, this made it sound more like a cosmetic plugin like the "Rest" plugin. I think changing it from "Watches over you while you AFK" to "Generates custom notifications and alerts for different events" would get more eyeballs on it.

The global debounce would probably be fine as a stopgap solution, I feel like it's rare that you'd actually need multiple different alerts to fire simultaneously anyway (Maybe if a Random event happens to spawn at the same moment your farming patches wrap)? But the global version should fix the issue where, for example, all of your Herb patches become available simultaneously, and it stops Watchdog from firing TTS alerts for all of them in the same tick.

**Comment by adamk33n3r** [comment]
How about this? 
>Create custom alerts for different events like messages, stats, or built-in notifications

Oh man I bet if all your herb patches finish that'll blast your ears! 😅 I might have some time to work on this today.

**Comment by Marstead** [comment]
> 

That sounds great! I actually found this because of a RL Issue I had opened requesting custom alerts, and someone recently commented "I know Watchdog solves this, but I still want it in base RuneLite..." and I was like, "*That's* what Watchdog does???" 😂 Thanks for being responsive!

**Comment by adamk33n3r** [comment]
That someone was me....I commented that on your issue HAHA!

**Comment by adamk33n3r** [comment]
@Marstead would you be willing to test out a build? I don't play much right now, so it'd be great if you could. If so, you can reach out to me on discord `@adamk33n3r#1933`

**Comment by Marstead** [comment]
> @Marstead would you be willing to test out a build? I don't play much right now, so it'd be great if you could. If so, you can reach out to me on discord `@adamk33n3r#1933`

Sure, will do!
