### ISSUE TITLE
[Feature] item quantity options

### ISSUE THREAD

**Issue by KaiThorpe** [adamk33n3r/runelite-watchdog#69]
Would love to have a > (greater than), < (less than), = (equal to), != (not equal to) <= (greater than or equal to), >= (less than or equal to) options for item quantity in inventory events rather than what we currently have which is just a specific amount maybe also

**Comment by adamk33n3r** [comment]
I'd like to do this for some other things too like the skill changed alert. It just seemed complicated at the time. But now with inventory alerts, it does make even more sense since you can pick up multiple at a time.

The one question I have is if we'd only alert on the first time it hits the condition, or every time. Like, if it's >9 then will it alert at 10 and 11 and 12 etc.

**Comment by adamk33n3r** [comment]
This was actually done in 878d1901734de250a67f66e374b0f01a35f5fe3e
