### ISSUE TITLE
Allow larger debounce values via UI

### ISSUE THREAD

**Issue by CreativeTechGuy** [adamk33n3r/runelite-watchdog#77]
Currently the UI limits debounce values to 60,000 but if you edit the JSON it'll happily allow much larger numbers. Can the UI be unbounded (or some extremely high number eg: max_int)?

Use Case: The new Forestry events often involve spawning and despawning things over the span of multiple minutes. I would only like one alert for the very first time but since the UI only goes up to one minute, it ends up alerting in the middle of the event too.

Should be as easy as changing this value if this gets approved. :)

https://github.com/adamk33n3r/runelite-watchdog/blob/79010643136a5487a04cc8074e2a653096df5282/src/main/java/com/adamk33n3r/runelite/watchdog/ui/panels/AlertPanel.java#L281

**Comment by CreativeTechGuy** [comment]
For convenience, I created a PR ahead of time. Feel free to reject the PR if it goes against your vision.

**Comment by Cisney-Gassai** [comment]
I'm actually having the same issue with the same use case, on two of the three events I get the notification fired 2 or 3 times because 1m is not enough.

**Comment by adamk33n3r** [comment]
This was actually already suggested in #40. My stance was essentially "if I see a bigger need for it I'll think about it". The use case from #40 was just so weird, that it didn't seem that necessary. My only concern is supporting such large numbers from a visual standpoint since it's in milliseconds it'll kinda be ugly. That being said, I'm ok with the change 👍🏻
