### ISSUE TITLE
In-game loot drop chat message not recognized for chat alert.

### ISSUE THREAD

**Issue by iatethedinosaurs** [adamk33n3r/runelite-watchdog#9]
Hello, I love your plugin and have found so much utility from it that it's become a must have for me.

I seem to be having an issue and hopefully it's not something that I just overlooked. 
I'm trying to setup different sounds for different ranges of loot drop values (once I figure out how to use the glob patterns). But the chat alert doesn't seem to recognize the loot drop notification chat message that is sent when you have the loot threshold setup in the in-game Chat options.

Here is the message I'm talking about: 
![image](https://user-images.githubusercontent.com/20849321/205587585-35601268-9928-4fdf-9914-044023954376.png)

and here is how I have the chat alert setup:
![image](https://user-images.githubusercontent.com/20849321/205587436-19fecbcc-be98-49ca-8079-559747e01b35.png)

Thank you again for your plugin!

**Comment by salverrs** [comment]
Not the plugin creator but I think this issue is to do with the text colour formatting.

Currently, in order to match text that's coloured you need to add a wild card to the beginning and end of your text.

For example, in order to match different drop value ranges, you would add these as seperate chat message alerts:
```
*Valuable drop: *([0-9],??? coins)*
*Valuable drop: *([0-9][0-9],??? coins)*
*Valuable drop: *([0-9][0-9][0-9],??? coins)*
*Valuable drop: *([0-9],???,??? coins)*
*Valuable drop: *([0-9][0-9],???,??? coins)*
```

**Comment by adamk33n3r** [comment]
Oh I didn't even think about the colors interfering with that. I'm pretty sure I can strip colors from the text when I do the matching. I'll add that to the next release.

Regarding your last question, no not currently any  way using glob patterns. We'd have to fully support regex. Which.....I could do. I just didn't do that initially because regex is pretty complicated and figured most people could understand globs. I could add regex as a switch for people who want more control.

**Comment by adamk33n3r** [comment]
I forgot I was going to mention, the reason this works `*Valuable drop: *([0-9],??? coins)*` is actually a bug. It's because the `[0-9]` is getting passed through to the internal regex. My code should actually be escaping things like that so that they're not mixed, but glad it works for now haha. I'll look into enabling regex fully.

**Comment by iatethedinosaurs** [comment]
That would be neat. Hopefully others would be able to find some interesting uses from having a fully supported regex too.
Interesting that it's actually a bug, but happy to have it for now.
Thank you for looking into potentially supporting regex fully. I really appreciate it!

**Comment by iatethedinosaurs** [comment]
I'm a bit stumped. So `*Valuable drop: *([5-9],??? coins)*` works as it should for values between 5k-9,999 coins. However, it also fires, as an example, for a Rune 2h sword (37,966 coins).  Which I guess fits the criteria, but I thought that the range there would only be one digit, rather than 2. Or is it just something funky going on cause it's using the internal regex?

**Comment by adamk33n3r** [comment]
Ya so since stuff isn't being escaped, those parentheses are actually going to the regex as groups. So it's not matching it directly to a paren. So it's effectively like you have `*Valuable drop: *[5-9],??? coins*` which makes "anything" work for "before the digit".

You can try putting backslashes before the parens like this `*Valuable drop: *\([5-9],??? coins\)*`. I _think_ that will work.

**Comment by adamk33n3r** [comment]
Actually, can you try using two backslashes before each paren? I think Java might be the culprit here 😂 I think you actually need `\\(`

**Comment by iatethedinosaurs** [comment]
Unfortunately that doesn't seem to work either. Still stops firing altogether with double backslashes.

**Comment by iatethedinosaurs** [comment]
No worries! You've done amazing work! Happy that we got it figured out and that it's going to be looked at for the new version! :) To get that jar working with all my other plugins, I would have to get the RuneLite dev client setup, right? Since I would be sideloading the RC of this plugin? I'll most likely wait until the next version is released. I look forward to checking out the new stuff included in it! 

Thank you again for your work and this awesome plugin! It really is a hidden gem with only ~450 installs and I wish more people knew how great it is. :)

**Comment by adamk33n3r** [comment]
Ya, if you wanted to actually use it for normal play. I was just saying if you wanted to check it out temporarily just to see if it works and if you like it etc.

But thank you for the kind words. I'm thankful for the installs that I have, but if you have any ideas to get the word out there or to make it better feel free to reach out!

**Comment by iatethedinosaurs** [comment]
I tried launching the RC with that command it seems to still load all my other plugins. It does look like it correctly loaded the RC, since I have the Sound Fired alert. Not sure if there's a conflict in the configuration (from old version vs new version), but I can't seem to get the Set Allow In-Focus to stay on for any alert. It resets to Off whenever I save the alert.

On a side note, I am digging the new panel design. It's really nice!

I'll see if I can come up with anything. I was thinking of making a Reddit post showcasing some possibilities of the plugin. One example being that it allows for different notification sounds for different notifications, rather than having just one set sound used for everything.
